http:
  routers:

    unraid:
      entryPoints:
        - websecure
      rule: 'Host(`unraid.DOMAIN`)'
      service: unraid

  services:
    unraid:
      loadBalancer:
        servers:
          - url: "http://UNRAID" # unraid ip + http port
