version: "3.7"

services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - proxy
    # ports:
    #   - 80:80
    #   - 3012:3012
    volumes:
      - ${DATA_PATH}/vaultwarden:/data
    environment:
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true # Send invitation using admin page
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN} # openssl rand -base64 48
      # - LOG_FILE=/data/vaultwarden.log
      # - LOG_LEVEL=warn
      - DOMAIN=https://vault.${DOMAIN}
      # - SMTP_HOST=${VAULTWARDEN_STMP_HOST}
      # - SMTP_FROM=${VAULTWARDEN_STMP_FROM}
      # - SMTP_PORT=${VAULTWARDEN_STMP_PORT}
      # - SMTP_SSL=true
      # - SMTP_USERNAME=${VAULTWARDEN_STMP_USER}
      # - SMTP_PASSWORD=${VAULTWARDEN_STMP_PASS}
      # - SMTP_AUTH_MECHANISM=${VAULTWARDEN_SMTP_AUTH}
      # - SMTP_ACCEPT_INVALID_CERTS=${VAULTWARDEN_INVALID_CERTS}
      # - SMTP_ACCEPT_INVALID_HOSTNAMES=${VAULTWARDEN_INVALID_HOSTNAMES}
    labels:
      - traefik.enable=true
      # Web UI
      - traefik.http.routers.vaultwardenWeb-rtr.entrypoints=websecure
      - traefik.http.routers.vaultwardenWeb-rtr.rule=Host(`vault.${DOMAIN}`)
      - traefik.http.routers.vaultwardenWeb-rtr.priority=1
      - traefik.http.routers.vaultwardenWeb-rtr.service=vaultwardenWeb-svc
      - traefik.http.services.vaultwardenWeb-svc.loadbalancer.server.port=80
      # WebSocket Notifications Hub
      - traefik.http.routers.vaultwardenHub-rtr.entrypoints=websecure
      - traefik.http.routers.vaultwardenHub-rtr.rule=(Host(`vault.${DOMAIN}`) && Path(`/notifications/hub`))
      - traefik.http.routers.vaultwardenHub-rtr.priority=2
      - traefik.http.routers.vaultwardenHub-rtr.service=vaultwardenHub-svc
      - traefik.http.services.vaultwardenHub-svc.loadbalancer.server.port=3012
      # Admin Page
      - traefik.http.routers.vaultwardenAdmin-rtr.entrypoints=websecure
      - traefik.http.routers.vaultwardenAdmin-rtr.rule=(Host(`vault.${DOMAIN}`) && Path(`/admin`))
      - traefik.http.routers.vaultwardenAdmin-rtr.priority=3
      - traefik.http.routers.vaultwardenAdmin-rtr.service=vaultwardenWeb-svc

networks:
  proxy:
    external: true
