version: "3.7"

services:

  db:
    image: postgres:14-alpine
    container_name: gitea-db
    restart: unless-stopped
    networks:
      - gitea
    environment:
      - POSTGRES_PASSWORD=${GITEA_DB_PASS}
      - POSTGRES_USER=${GITEA_DB_USER}
      - POSTGRES_DB=${GITEA_DB_NAME}
    volumes:
      - ${DATA_PATH}/gitea/db:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    healthcheck:
      test: pg_isready -U ${GITEA_DB_USER} -d ${GITEA_DB_NAME}
      interval: 10s
      timeout: 2s
      retries: 10

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    networks:
      - proxy
      - gitea
    # ports:
    #   - 3000:3000
    #   - 2222:22
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${DATA_PATH}/gitea/data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=666
      - SSH_LISTEN_PORT=22
      - ROOT_URL=https://gitea.${DOMAIN}
      - DOMAIN=gitea.${DOMAIN}
      - SSH_DOMAIN=gitea.${DOMAIN}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASS}
      # - GITEA__mailer__ENABLED=true
      # - GITEA__mailer__FROM=${GITEA__mailer__FROM}
      # - GITEA__mailer__MAILER_TYPE=smtp
      # - GITEA__mailer__HOST=${GITEA__mailer__HOST}
      # - GITEA__mailer__IS_TLS_ENABLED=false
      # - GITEA__mailer__USER=${GITEA__mailer__USER:-apikey}
      # - GITEA__mailer__PASSWD="""${GITEA__mailer__PASSWD}"""
      # - GITEA__mailer__SKIP_VERIFY=true
    labels:
      - traefik.enable=true
      # web
      - traefik.http.routers.giteaWeb-rtr.entrypoints=websecure, expose
      - traefik.http.routers.giteaWeb-rtr.rule=Host(`gitea.${DOMAIN}`)
      - traefik.http.routers.giteaWeb-rtr.service=giteaWeb-svc
      - traefik.http.services.giteaWeb-svc.loadbalancer.server.port=3000
      # ssh
      - traefik.tcp.routers.giteaSSH-rtr.entrypoints=ssh
      - traefik.tcp.routers.giteaSSH-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.giteaSSH-rtr.service=giteaSSH-svc
      - traefik.tcp.services.giteaSSH-svc.loadbalancer.server.port=22

networks:
  gitea:
    name: gitea
  proxy:
    external: true
