version: 3.7"

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 666:666
      - 8443:8443
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
    volumes:
      - ${DATA_PATH}/traefik/certificates:/letsencrypt:rw
      - ${DATA_PATH}/traefik/config:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik-rtr.service=api@internal

networks:
  proxy:
    name: proxy
