version: "3.7"

services:

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.draw-rtr.entrypoints=websecure
      - traefik.http.routers.draw-rtr.rule=Host(`draw.${DOMAIN}`)
      - traefik.http.routers.draw-rtr.service=draw-svc
      - traefik.http.services.draw-svc.loadbalancer.server.port=80

networks:
  proxy:
    external: true
